### ISSUE TITLE
Exception "could not set a field value by reflection" with enum and "object references an unsaved transient instance : save the transient instance before flushing"

### ISSUE THREAD

**Issue by kaoh** [kwon37xi/hibernate4-memcached#17]
I'm switching to memcached and since the introduction I get this error when an Enum value for a cached object is deserialized. 
Also a try to save a new created entity is erroneously rejected with "object references an unsaved transient instance"

What could be the reason? In the debugger the cached enum value and the target object are looking good, all POJO criterias are met, it was working before.When turning off the cache all tests are working.

The deserialization exception is raised in around org/hibernate/tuple/entity/AbstractEntityTuplizer.java:712 / org/hibernate/property/DirectPropertyAccessor.java:122

org.springframework.orm.jpa.JpaSystemException: org.hibernate.PropertyAccessException: could not set a field value by reflection setter of foobar.Person.gender; nested exception is javax.persistence.PersistenceException: org.hibernate.PropertyAccessException: could not set a field value by reflection setter of foobar.Person.gender

**Comment by kwon37xi** [comment]
No further information.
