### ISSUE TITLE
ClassNotFoundException: kr.pe.kwonnam.hibernate4memcached.spymemcached.SpyMemcachedAdapter

### ISSUE THREAD

**Issue by yaderbh** [kwon37xi/hibernate4-memcached#18]
Hello,

I'm getting a ClassNotFoundException while my application is booting up.

Looking over the packages, it seems its completely missing from the JAR itself:

http://mvnrepository.com/artifact/kr.pe.kwonnam.hibernate4memcached/hibernate4-memcached-core/0.6

Packages

kr.pe.kwonnam.hibernate4memcached
kr.pe.kwonnam.hibernate4memcached.memcached
kr.pe.kwonnam.hibernate4memcached.regions
kr.pe.kwonnam.hibernate4memcached.strategies
kr.pe.kwonnam.hibernate4memcached.timestamper
kr.pe.kwonnam.hibernate4memcached.util

Where is kr.pe.kwonnam.hibernate4memcached.spymemcached package?

**Comment by kwon37xi** [comment]
You're project should depends on hibernate4-memcached-spymemcached-adapter.

http://mvnrepository.com/artifact/kr.pe.kwonnam.hibernate4memcached/hibernate4-memcached-spymemcached-adapter

I designed this library to be able to plug memcached implementations. But there is only one implementation - spymemcached.

**Comment by yaderbh** [comment]
Thank you.

Looks like I don't have something configured correctly. All hibernate queries are still landing on the database.

I have many entities like the following:

```
@Cache(region = "users", usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Entity
@Table(name = "users")
public class User implements Serializable {

	public enum AccountStatus {
		UNVERIFIED, VERIFIED
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id")
	private Integer id;

	@Column(name = "username")
	private String username;

	@Column(name = "latitude")
	private Double latitude;

	@Column(name = "longitude")
	private Double longitude;
}
```

With the following properties:

```
        properties.setProperty("hibernate.cache.use_second_level_cache", "true");
        properties.setProperty("hibernate.cache.use_query_cache", "true");
        properties.setProperty("hibernate.cache.default_cache_concurrency_strategy", "NONSTRICT_READ_WRITE");
        properties.setProperty("hibernate.cache.region.factory_class", "kr.pe.kwonnam.hibernate4memcached.Hibernate4MemcachedRegionFactory");
        properties.setProperty("hibernate.cache.use_structured_entries", "false");
        properties.setProperty("h4m.adapter.class", "kr.pe.kwonnam.hibernate4memcached.spymemcached.SpyMemcachedAdapter");

        properties.setProperty("h4m.adapter.spymemcached.hosts", "localhost:11211");
        properties.setProperty("h4m.adapter.spymemcached.hashalgorithm", "KETAMA_HASH");
        properties.setProperty("h4m.adapter.spymemcached.operation.timeout.millis", "5000");
        properties.setProperty("h4m.adapter.spymemcached.transcoder", "kr.pe.kwonnam.hibernate4memcached.spymemcached.KryoTranscoder");
        properties.setProperty("h4m.adapter.spymemcached.cachekey.prefix", "h4m");
        properties.setProperty("h4m.adapter.spymemcached.kryotranscoder.compression.threashold.bytes", "20000");

        properties.setProperty("h4m.expiry.seconds", "3600");
```

I'm running memcached with -vv option but I don't see any activity. What could be the issue?

**Comment by kwon37xi** [comment]
It's not easy to feagure out with your information.
Please set the application log level to "debug", and look what the log says.
