### ISSUE TITLE
NullPointerException in deserialized CachedDateTimeZone.getInfo

### ISSUE THREAD

**Issue by luversof** [kwon37xi/hibernate4-memcached#23]
https://github.com/JodaOrg/joda-time/issues/307

joda datetime을 사용하면 링크한 이슈가 발생합니다.

KryoTranscoder에서 serialize시 문제인 듯 합니다.

좋은 하루 되세요~

**Comment by kwon37xi** [comment]
해당 링크의 답변에도 나와있듯이, 외부 직렬화 라이브러리를 추가해줘야 합니다.

Kryo는 모든 상황에 대한 직렬화를 다 처리하지 못합니다.

joda-time의 경우 https://github.com/magro/kryo-serializers 를 통해 joda-time 관련 직렬화 모듈을 추가해줘야 합니다.
이를 추가하려면 [KryoTranscoder](https://github.com/kwon37xi/hibernate4-memcached/blob/master/hibernate4-memcached-spymemcached-adapter/src/main/java/kr/pe/kwonnam/hibernate4memcached/spymemcached/KryoTranscoder.java) 의 `protected Kryo createKryo`를 Override 한 새로운 KryoTranscoder 를 만들어서 `h4m.adapter.spymemcached.transcoder`로 지정해주면 됩니다.

여기서 주의하실 것이 있는데 현재 hibernate4-memcached는 Kryo 2.x 버전을 사용한다는 점입니다. kryo-serializers 도 Kryo 2.x 에 맞는 버전으로 사용해주셔야 합니다.

**Comment by kwon37xi** [comment]
답변을 완료하였으므로 close합니다.

**Comment by luversof** [comment]
답변 감사드립니다. 해당 처리로 정상 동작하는 것을 확인하였습니다. (__)
좋은 하루 되세요.
